language: go

go:
  - 1.15.x

script:
  - go test -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v vendor/`

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true